### ISSUE TITLE
Current bugs

### ISSUE THREAD

**Issue by lauman64** [leslie-alldridge/community-todo#10]
- There is a section in the JS where I can't get the 'alerts' to activate (I've marked it in the code).
-Complete button turns any value from the Ordered List to a '0' when moved to the UnOrdered Completed List. 
Can you take a look for me and see where I've gone wrong? @leslie-alldridge

**Comment by leslie-alldridge** [comment]
yep i'll have a look tonight

**Comment by leslie-alldridge** [comment]
@lauman64 I've added a span to each line item with an X. If you click the X the item vanishes from the UI. However, it still lives in the array. So what I tried doing next, was appending a number to each classname so line items are named classname1 classname2 etc etc. - to make them unique LI's

Next, if we can find a way to split the classname and take the number portion only, that could be passed through to the removefromarray function. 

Because I found that without the right number, the remove function just removes the most recent addition to the array, even if the user clicks the first one for removal. 

I added notes from line 107 onward and the console will display each classname for you. Cheers
